import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import { Inter } from "next/font/google";
import "./globals.css";
import { auth } from "@/auth";
import { headers } from "next/headers";
import { Provider } from "react-redux";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth.api.getSession({
    headers: await headers()
  });
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased bg-[#f5f5f5]`}>
        {children}
      </body>
    </html>
  );
}
